spring:
  application:
    name: local-travel
  profiles:
    active: dev
    include: secret
  cloud:
    aws:
      region:
        static: "ap-northeast-2"
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 7776000 # 90일

  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100

server:
  port: 8081
